/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import sistemaempleados.ConexionSQLServer;
import javax.swing.JOptionPane; 
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author marin
 */
public class triggers extends javax.swing.JFrame {

    /**
     * Creates new form triggers
     */
    public triggers() {
        initComponents();
        this.setLocationRelativeTo(null);
        iconoEnBD();
    }
    public void iconoEnBD() {
        URL url = getClass().getResource("/imagenes/ICONOENBD.png");
        ImageIcon icono = new ImageIcon(url);
        setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxReporte = new javax.swing.JComboBox<>();
        botonGenerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxReporte.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        comboBoxReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una acción", "REGISTRO", "ELIMINACIÓN", "MODIFICACIÓN" }));
        jPanel1.add(comboBoxReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 210, 30));

        botonGenerar.setBackground(new java.awt.Color(153, 153, 255));
        botonGenerar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        botonGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte_icono.png"))); // NOI18N
        botonGenerar.setText("GENERAR REPORTE");
        botonGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGenerarMouseClicked(evt);
            }
        });
        jPanel1.add(botonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 80));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 70, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes_menu.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGenerarMouseClicked
        // TODO add your handling code here:
        ConexionSQLServer con = new ConexionSQLServer(); 
        Connection conexion = con.getConnection(); 
        if(comboBoxReporte.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(getParent(), "SELECCIONE UNA ACCIÓN", "RECORDATORIO", JOptionPane.INFORMATION_MESSAGE);
        }else if(comboBoxReporte.getSelectedIndex()==1){
            try {
            String ruta = System.getProperty("user.dir") + "/src/reporte/report2.jasper";
            JasperReport jr = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            JasperPrint pt = JasperFillManager.fillReport(ruta, null, conexion);
            JasperViewer jv = new JasperViewer(pt, false);
            jv.setVisible(true);
        } catch (Exception e) {
        }
        }else if(comboBoxReporte.getSelectedIndex()==3){
              try {
            String ruta = System.getProperty("user.dir") + "/src/reporte/report3.jasper";
            JasperReport jr = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            JasperPrint pt = JasperFillManager.fillReport(ruta, null, conexion);
            JasperViewer jv = new JasperViewer(pt, false);
            jv.setVisible(true);
        } catch (Exception e) {
        } 
        }else if(comboBoxReporte.getSelectedIndex()==2){
              try {
            String ruta = System.getProperty("user.dir") + "/src/reporte/report4.jasper";
            JasperReport jr = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            JasperPrint pt = JasperFillManager.fillReport(ruta, null, conexion);
            JasperViewer jv = new JasperViewer(pt, false);
            jv.setVisible(true);
        } catch (Exception e) {
        }
        }
        
    }//GEN-LAST:event_botonGenerarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        VentanaInicio vi = new VentanaInicio(); 
        vi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(triggers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(triggers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(triggers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(triggers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new triggers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerar;
    private javax.swing.JComboBox<String> comboBoxReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
